# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec2cb78875b57e139ff9925b3174417369db1c1b9a6febe8e100733db416c104c54b45e4a4667d2749057a4a6f75cb13c96c716055c3f6ea260599a08ba96d3

test:
  secret_key_base: cde5d85812b6e62c9ae742c50fbdf27fcc62b49ecdbe7d8735e606dfb7bd8c864f8de028c7cdbcfc441d17d28a32b17355bf08281f36ae35936a7fce494cdc82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
